require: rubocop-minitest

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  SuggestExtensions: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Style/WordArray:
  EnforcedStyle: brackets

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Layout/EmptyLinesAroundAccessModifier:
  EnforcedStyle: only_before

Metrics:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Gemspec/RequireMFA:
  Enabled: false
